name: Print to PDF

on:
  push:
    branches: [ main ]

jobs:
  portrait_en:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: browser-actions/setup-chrome@v1
      - run: chrome --version
      - uses: actions/checkout@v4
      - name: html to portrait_en.pdf
        run: chromium --headless=new --disable-gpu --print-to-pdf="portrait_en.pdf" ./public/sheet.html
      - name: upload portrait_en
        id: upload_portrait_en
        uses: svenstaro/upload-release-action@v2
        with:
          file: portrait_en.pdf
          overwrite: true
      - name: print portrait_en.pdf path
        run: echo ${{ steps.upload_portrait_en.outputs.browser_download_url }}
      - name: git
        run: |
          # git --version
          # setup the username and email.
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git fetch --all
          git checkout i18n_german
          git status
          git merge main --no-ff
      - name: html to portrait_de.pdf
        run: chromium --headless=new --disable-gpu --print-to-pdf="portrait_de.pdf" ./public/sheet.html
      - name: upload portrait_de
        id: upload_portrait_de
        uses: svenstaro/upload-release-action@v2
        with:
          file: portrait_de.pdf
          overwrite: true
      - name: print portrait_de.pdf path
        run: echo ${{ steps.upload_portrait_de.outputs.browser_download_url }}
