name: Print to PDF

on:
  push:
    branches: [ main ]

jobs:
  portrait_en:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: html to pdf
        uses: fifsky/html-to-pdf-action@master
        with:
          htmlFile: ./public/sheet.html
          outputFile: ./portrait_en.pdf
      - name: upload pdf
        uses: svenstaro/upload-release-action@v2
        with:
          file: portrait_en.pdf
          overwrite: true
      - name: print pdf path
        run: echo "$browser_download_url"
