name: Translate German

on:
  push:
    branches: [ main ]

jobs:
  build-version:

    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: git
      run: |
        # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
        # branches are named:
        #  remotes/origin/i18n_german
        #  remotes/origin/main
        #  remotes/origin/master
        git --version
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git status
        git checkout origin/i18n_german
        git merge origin/main --no-ff
        git push origin HEAD:i18n_german
